"""migrate1.0

Revision ID: 5954e2f43a2e
Revises: 
Create Date: 2024-01-03 21:28:35.620505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5954e2f43a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prova',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('uc', sa.String(length=100), nullable=False),
    sa.Column('tempo_admissao', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('avaliada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versao_prova',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_prova',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.Integer(), nullable=True),
    sa.Column('disp_resultado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['prova.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_versao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pergunta', sa.String(length=200), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questao_versao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta_aluno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_prova_id', sa.Integer(), nullable=False),
    sa.Column('questao_versao_id', sa.Integer(), nullable=False),
    sa.Column('opcao_id', sa.Integer(), nullable=True),
    sa.Column('resposta_texto', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['aluno_prova_id'], ['aluno_prova.id'], ),
    sa.ForeignKeyConstraint(['opcao_id'], ['opcao.id'], ),
    sa.ForeignKeyConstraint(['questao_versao_id'], ['questao_versao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta_aluno')
    op.drop_table('opcao')
    op.drop_table('questao_versao')
    op.drop_table('aluno_prova')
    op.drop_table('versao_prova')
    op.drop_table('prova')
    # ### end Alembic commands ###
