"""migrate1.0

Revision ID: 39d66151e816
Revises: 
Create Date: 2024-01-05 23:57:01.673403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d66151e816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala', sa.String(length=100), nullable=False),
    sa.Column('edificio', sa.String(length=100), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('sala')
    # ### end Alembic commands ###
